package kg.euler;

public class Day0029 {
    public static void main(String[] args) {
        long result = solution(2, 6);
        System.out.println("result is " + result);
    }

    // How many distinct terms are in the sequence generated by a^b
    // for 2 <= a <= 100
    // and 2 <= b <= 100 ?
    static long solution(int min, int max) {
        int expAmtWithDups = (max-1) * (max - 1);

        for(int i = min; i <= max; i++) {
            for(int j = min; j <= max; j++) {
                if(i < j && i % j == 0) {
                    expAmtWithDups --; //9518 wrong
                }
            }
        }
        return expAmtWithDups;
    }
}